/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: e79ac3c64304a17c8ee9aca5e64bbcf3)
declare namespace Cloudflare {
	interface Env {
		AGENTS_CHATSTORE: string;
		RWSDK_CHATSTORE: string;
		REALTIME_KEY: string;
		WEBSOCKET_AGENT_NAME: string;
		TINYBASE_SYNC_ROUTE: string;
		REALTIME_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").RealtimeDurableObject>;
		CHATSTORE_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").ChatDurableObject>;
		WEBSOCKET_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").WebsocketAgent>;
		CHAT_AGENT_SDK_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").ChatAgentSDKDO>;
		TINYBASE_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").TinyBaseDurableObject>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
