/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: 47f6d909c559b3233ab6b69844ec7dbd)
declare namespace Cloudflare {
	interface Env {
		AGENTS_CHATSTORE: string;
		RWSDK_CHATSTORE: string;
		REALTIME_KEY: string;
		WEBSOCKET_AGENT_NAME: string;
		TINYBASE_SYNC_ROUTE: string;
		ENV: string;
		OPENAI_API_KEY: string;
		REALTIME_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").RealtimeDurableObject>;
		CHATSTORE_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").ChatDurableObject>;
		WEBSOCKET_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").WebsocketAgent>;
		CHAT_AGENT_SDK_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").ChatAgentSDKDO>;
		CHAT_AGENT_AGENT_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").ChatAgentAgentDO>;
		TINYBASE_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").TinyBaseDurableObject>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AGENTS_CHATSTORE" | "RWSDK_CHATSTORE" | "REALTIME_KEY" | "WEBSOCKET_AGENT_NAME" | "TINYBASE_SYNC_ROUTE" | "ENV" | "OPENAI_API_KEY">> {}
}
