/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: d33cc7fc9dd21d0de6dfcce6216831e6)
declare namespace Cloudflare {
	interface Env {
		CHAT_ID: string;
		REALTIME_KEY: string;
		WEBSOCKET_AGENT_PATH: string;
		WEBSOCKET_AGENT_NAME: string;
		REALTIME_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").RealtimeDurableObject>;
		CHAT_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").ChatDurableObject>;
		WEBSOCKET_AGENT: DurableObjectNamespace<import("./src/worker").WebsocketAgent>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
